#!/usr/bin/env bats
#set -xe

: ${CLUSTER_NAME:=edwetl26-21}

load ../$STACK_NAME".stackdescriptor"
load ../helper/hdc/cli
load ../helper/smartsense-stack-prep

CLUSTER_FILE_NAME=$CLUSTER_NAME".clusterdescriptor.bash"
TAGS="$STACK_NAME $CLUSTER_NAME flex-less functional hdc-cli"

function get_ss_id() {
    cd /var/lib/cloudbreak-deployment/
    [[ $(cbd util get-usage latest | jq -r '.controller.smartSenseId') == 'A-99907550-C-47402263' ]] && echo true || echo false
}

function get_felx_id() {
    cd /var/lib/cloudbreak-deployment/
    [[ $(cbd util get-usage latest | jq -r ' .products[].components[] | select(.componentId=="HDCLOUD-AWS-HDP") | .instances[].flexSubscriptionId' | tail -1) == null ]] && echo true || echo false
}

function get_peak_nodes() {
    cd /var/lib/cloudbreak-deployment/
    echo $(cbd util get-usage latest | jq -r '.products[].components[] | select(.componentId=="HDCLOUD-AWS-HDP") | .instances[].peakUsage' | tail -1)
}

function check_sftp_status() {
    echo $(docker exec -i cbreak_smartsense_1 bash -c "grep 'File uploaded successfully to sftp server:a-99907550-c-47402263_hdcu-' /var/log/hst/hst-server.log")
}

@test "describe SmartSense command should return [A-99907550-C-47402263] id" {
    run describe-smartsensesubscription
    echo $output >&2

    [[ "$output" =~ "A-99907550-C-47402263" ]]
}

@test "list FLEX subscriptions should return with no value" {
    run list-flexsubscriptions SubscriptionID | head -c1 | wc -c
    echo $output >&2

    [[ "$output" -eq 0 ]]
}

@test "register FLEX subscription should be rejected" {
    run register-flexsubscription default FLEX-0000000000
    echo $output >&2

    [[ "$output" =~ "SmartSense subscription generated by Cloudbreak" && "$status" -ne 0 ]]
}

@test "validation error should be present for 'FlexSubscription' in validate-cli-skeleton" {
    INPUT_JSON_FILE=common/cluster-templates/autotest-edw26-flex-template.json

    list-cluster-types

    run validate-cli-skeleton --cli-input-json $INPUT_JSON_FILE
    echo $output >&2

    [[ "$output" =~ "Flex subscription could not be configured, because your SmartSense subscription is generated" && "$status" -ne 0 ]]
    # BUG-83411 [HDC Flex Usage] 'FlexSubscription' validation is missing from 'validate-cli-skeleton'
}

@test "validation error should be present for 'FlexSubscription' in cluster template" {
    INPUT_JSON_FILE=common/cluster-templates/autotest-edw26-flex-template.json

    list-cluster-types

    run create-cluster --cli-input-json $INPUT_JSON_FILE
    echo $output >&2

    [[ "$output" =~ "Flex subscription could not be configured, because your SmartSense subscription is generated." && "$status" -ne 0 ]]
    # BUG-83411 [HDC Flex Usage] 'FlexSubscription' validation is missing from 'validate-cli-skeleton'
}

@test "create HDP 2.6 EDW-ETL cluster [$TAGS]" {
    echo "STACK_NAME=${STACK_NAME}" > $CLUSTER_FILE_NAME
    echo "CLOUD_URL=${CLOUD_URL}" >> $CLUSTER_FILE_NAME
    echo "EMAIL=${EMAIL}" >> $CLUSTER_FILE_NAME
    echo "PASSWORD=${PASSWORD}" >> $CLUSTER_FILE_NAME
    echo "SSHKEY=${SSHKEY}" >> $CLUSTER_FILE_NAME
    echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $CLUSTER_FILE_NAME
    echo "TEMPLATE_VERSION=${TEMPLATE_VERSION}" >> $CLUSTER_FILE_NAME
    echo "CB_VERSION=${CB_VERSION}" >> $CLUSTER_FILE_NAME

    INPUT_JSON_FILE=common/cluster-templates/${CLUSTER_NAME}-template.json
    echo "INPUT_JSON_FILE=${INPUT_JSON_FILE}" >> $CLUSTER_FILE_NAME

    run create-cluster --cli-input-json $INPUT_JSON_FILE
    echo $output >&2

    load ../$CLUSTER_NAME".clusterdescriptor"
}

@test "Validate 'cbd util get-usage latest' SmartSense ID is [A-99907550-C-47402263]" {
    [[ $(usage_json_checker get_ss_id) =~ "true" ]]
}

@test "Validate 'cbd util get-usage latest' FLEX ID is null" {
    [[ $(usage_json_checker get_felx_id) =~ "true" ]]
}

@test "Validate 'cbd util get-usage latest' peak usage is 5" {
    [[ $(usage_json_checker get_peak_nodes) =~ ^5 ]]
}

@test "Validate 'File uploaded successfully to sftp server' from cbreak_smartsense container" {
    [[ $(usage_json_checker check_sftp_status) =~ "a-99907550-c-47402263" ]]
}

@test "resize cluster - worker nodes [$TAGS]" {
    resize --scaling-adjustment 2 --node-type worker
}

@test "resize - wait for available nodes [$TAGS]" {
    tenminuteslater=$(($SECONDS+600))
    are_available=false

    while [ $SECONDS -lt $tenminuteslater ] && [ $are_available == false ]
    do
	    sleep 30
	    are_available=$(describe-cluster | jq -r '.Status=="AVAILABLE"')
    done

    [[ $are_available == true ]]
}

@test "Validate 'cbd util get-usage latest' peak usage is 7" {
    [[ $(usage_json_checker get_peak_nodes) =~ ^7 ]]
}

@test "Terminate cluster [$TAGS]" {
    run terminate-cluster
}

@test "Terminate cluster - wait for finish [$TAGS]" {
    threeminuteslater=$(($SECONDS+180))
    stillexist=10 # anything which is greater than 0

    while [ $SECONDS -lt $threeminuteslater ] && [ $stillexist -gt 0 ]
    do
  	    sleep 30
	    stillexist=$( list-clusters | jq -r ".[] | select(.ClusterName==\"${CLUSTER_NAME}\") | length " )
    done

    [[ ${stillexist} -eq 0 ]]
}

@test "Terminate - check clusters status in list - not in the list [$TAGS]" {
    [[ $(list-clusters | jq -r ".[] | select(.ClusterName==\"${CLUSTER_NAME}\") | length ") -eq 0 ]]
}

@test "Teardown - rm cluster descriptor [$TAGS]" {
    rm "${CLUSTER_NAME}".clusterdescriptor.bash
}
